version: '3.8'

services:
  postgres:
    container_name: course_management_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2001
      - POSTGRES_DB=course_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: